- name: Create a GCP Free Tier VM
  hosts: localhost
  gather_facts: no
  vars:
    gcp_project: "<your-gcp-project-id>"
    gcp_zone: "us-central1-a"
    machine_type: "e2-micro"
    disk_size: 30
    disk_type: "pd-standard"
    service_account_file: "~/.gcp/ansible-key.json"
    network_name: "default"

  tasks:
    - name: Create VM instance
      google.cloud.gcp_compute_instance:
        name: ansible-free-vm
        machine_type: "{{ machine_type }}"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ service_account_file }}"
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: "projects/debian-cloud/global/images/family/debian-11"
              disk_size_gb: "{{ disk_size }}"
              disk_type: "{{ disk_type }}"
        network_interfaces:
          - network:
              name: "{{ network_name }}"
            access_configs:
              - name: External NAT
                type: ONE_TO_ONE_NAT
      register: vm_instance

    - name: Display VM details
      debug:
        var: vm_instance
