- name: Configure GCP Free-Tier VM
  block:
    - name: Ensure a test directory exists in the remote user's home directory
      file:
        path: "~/test"
        state: directory
        mode: "0755"

    - name: Create a test file in the test directory
      copy:
        content: "Hello from Ansible!"
        dest: "~/test/hello.txt"
        mode: "0644"
